name: Deploy to S3

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file from GitHub secrets
        run: |
             cat <<EOF > .env
             VITE_S3_BUCKET_NAME=${{ secrets.VITE_S3_BUCKET_NAME }}
             VITE_AWS_REGION=${{ secrets.VITE_AWS_REGION }}
             VITE_AWS_ACCESS_KEY_ID=${{ secrets.VITE_AWS_ACCESS_KEY_ID }}
             VITE_AWS_SECRET_ACCESS_KEY=${{ secrets.VITE_AWS_SECRET_ACCESS_KEY }}
             VITE_AWS_SESSION_TOKEN=${{ secrets.VITE_AWS_SESSION_TOKEN }}
             EOF

      - name: Check .env content
        run: head -n 4 .env

      - name: Build the project
        run: npm run build

      - name: Clean up .env
        run: rm .env

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.VITE_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.VITE_AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.VITE_AWS_SESSION_TOKEN }}
          aws configure set region ${{ secrets.VITE_AWS_REGION }}

      - name: ☁️ Deploy to S3
        run: |
          aws s3 sync ./dist s3://factoriaf5.emma.fase2 --delete --acl public-read

      - name: ✅ Check Deployment
        run: echo "🚀 ¡Despliegue completado correctamente en S3!"
